spring.application.name=hireiq-backend

spring.datasource.url=jdbc:mysql://localhost:3306/hireiq_db
spring.datasource.username=root
spring.datasource.password=Sai@2006

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

gemini.api.key=AIzaSyAN1WliAjuu9X2pXTzjI9DQHKA3WsY-iqc
